services:
  - type: web
    name: glassrain
    runtime: python
    buildCommand: pip install -r final_glassrain/requirements.txt
    startCommand: cd final_glassrain && gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 3000
